#!/usr/bin/env bash
set -euo pipefail

PROJECT_ID="${PROJECT_ID:?Set PROJECT_ID}"
REGION="${REGION:-us-central1}"
JOB_NAME="${JOB_NAME:-sdp-bq-masker}"

: "${SOURCE_TABLE:?Set SOURCE_TABLE}"
: "${TARGET_TABLE:?Set TARGET_TABLE}"
: "${FREETEXT_COLUMNS:?Set FREETEXT_COLUMNS}"
: "${INSPECT_TEMPLATE:?Set INSPECT_TEMPLATE}"
: "${DEIDENTIFY_TEMPLATE:?Set DEIDENTIFY_TEMPLATE}"

gcloud run jobs execute "${JOB_NAME}" \
  --project="${PROJECT_ID}" \
  --region="${REGION}" \
  --update-env-vars="PROJECT_ID=${PROJECT_ID},SOURCE_TABLE=${SOURCE_TABLE},TARGET_TABLE=${TARGET_TABLE},FREETEXT_COLUMNS=${FREETEXT_COLUMNS},INSPECT_TEMPLATE=${INSPECT_TEMPLATE},DEIDENTIFY_TEMPLATE=${DEIDENTIFY_TEMPLATE},BATCH_SIZE=${BATCH_SIZE:-1000},DLP_LOCATION=${DLP_LOCATION:-global},DRY_RUN=${DRY_RUN:-false}" \
  --wait